### ISSUE TITLE
Optional parameters issue

### ISSUE THREAD

**Issue by Naxon** [tightenco/ziggy#67] opened 2017-08-26 09:54 UTC
Hi,

I small issue I bumped in today: I have the following route:
```
Route::get('players/{season?}', 'PlayersController@index')->name('players.index');
```

When trying to use it with Ziggy, even when sending the `season` parameter, it expects me to send it as `season?` (and it actually works when sending it as `season?`!). When not sending the `season` parameter I'm getting the very same error.

> Uncaught Ziggy Error: "season?" key is required for route "players.index"

**Comment by DanielCoulbourne** [comment] 2017-08-28 02:50
Thanks! I'll look into this.

**Comment by quickliketurtle** [comment] 2017-10-20 04:30
Hey @Naxon. 
I'm having trouble reproducing this. Is it still an issue? 

If so can you confirm that your route looks like this: 
`"players.index":{"uri":"players\/{season?}","methods":["GET","HEAD"],"domain":null}`
and you are calling it like this:
`route('players.index', { season: "1" })`

Thanks.

**Comment by DanielCoulbourne** [comment] 2017-10-20 18:05
I also can't replicate as of now. Going to close this for now.

**Closed by DanielCoulbourne** 2017-10-20 18:05 UTC
