### ISSUE TITLE
May you add support of querystring?

### ISSUE THREAD

**Issue by brunen9** [tightenco/ziggy#34] opened 2017-08-13 15:33 UTC
Hello. May you add support of querystring in route url? I mean something like this: `example.com/search?critter=bunny&gender=female&temperament=rabid&size=large&color=red`

**Comment by mattstauffer** [comment] 2017-08-13 21:39
Great idea! It's very possible with the current syntax although it (obviously) wouldn't work with the array syntax that's currently open in a pull request. I think that's true of laravels core route service as well so that'll be fine. Good thinking!

**Comment by JesseLeite** [comment] 2017-08-14 23:52
@mattstauffer I think it could work with array syntax, very similar to how it does in PHP/Laravel:

```php
route('events.venues.show', [123, 456, search => 'Grounds', active => true])
// Outputs '/events/123/venues/456?search=Grounds&active=true
```

And in JS:
```js
route('events.venues.show', [123, 456, {search: 'Grounds'}, {active: true}])
// Outputs '/events/123/venues/456?search=Grounds&active=true
```

It's not as ideal as PHP array syntax, but I'd gladly work on a PR if you like that implementation?

**Comment by DanielCoulbourne** [comment] 2017-08-14 23:54
I think this should probably be a separate argument from the existing route params.

For example a route like this:
```
/posts/1/comments?author=3&nesting_level=2
```

Could be expressed like this: 
```javascript
route('post.comments.index', {post: 1}, {author: 3, nesting_level: 2})
```

**Comment by JesseLeite** [comment] 2017-08-15 00:04
>I think this should probably be a separate argument from the existing route params.

I only disagree with the separate argument, because it's inconsistent with Laravel's `route()` (which already has a 3rd parameter [that does something different](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L707)).

Laravel is smart enough to count the required params, and treat all extra passed params as query string params.  What if Ziggy was smart enough to do same?  Maybe it could be more flexible than my original example though, for example:

```js
route('events.venues.show', [123, 456, {search: 'Grounds'}, {active: true}, {proximity: 12}])
route('events.venues.show', [123, 456, {search: 'Grounds', active: true, proximity: 12}])
// Both could '/events/123/venues/456?search=Grounds&active=true&proximity=12
```

^ Notice everything after the first two required parameters get object merged, then treated as query string params.  Thoughts?

**Comment by mattstauffer** [comment] 2017-08-15 06:12
Jesse, the problem is that the example you have is not the same as that array in Laravel. 

Daniel, that's one option but it's distinctly different from how Laravel handles it so just be cautious. :)

**Comment by JesseLeite** [comment] 2017-08-15 13:18
Yeah @mattstauffer good point, that is true it's not consistent.  I was thinking about this though, and there two competing aspects that ideally would benefit from more consistency with Laravel's `route()` function:

- 2nd argument consistency (for the route params to feel like Laravel)
- 3rd argument consistency (for the absolute param to feel like Laravel)

However, because of the differences between Javascript arrays/objects compared to PHP arrays, argument consistency with the 2nd argument will never be completely possible.  So I would challenge, should the consistency with the 3rd argument be sacrificed as well?

My last example above would allow for a pretty clean query string params object, and would preserve Laravel's 3rd `absolute` param for those that need it.

```js
var event = {id: 123, name: 'World Series'};
var venue = {id: 123, name: 'Rogers Centre'};
var queryStringParams = {search: 'Grounds', active: true, proximity: 12};

route('events.venues.show', [event, venue, queryStringParams])
```

Thoughts?

**Comment by JesseLeite** [comment] 2017-08-17 01:49
@mattstauffer @DanielCoulbourne Curious on your thoughts of my array syntax suggestion, would you accept a PR with that implementation?  Or would you prefer the use of object syntax with forced keys if they have extra query string params to append?  Or maybe both?

Either way, I think I feel pretty strongly about reserving the 3rd param for `absolute`, to stay as consistent with Laravel as possible 😬

No rush!  Just curious what you guys think 🙂

**Comment by DanielCoulbourne** [comment] 2017-08-18 02:28
Hey man sorry I haven't gotten back to you. I'll take a good look in a few minutes

**Comment by JesseLeite** [comment] 2017-08-18 02:53
No rush!

**Comment by DanielCoulbourne** [comment] 2017-08-18 06:43
Okay I'm still not 100% sure.

My two favorite options so far are 
`route('events.venues.show', [event, venue, queryStringParams])`
and `route('events.venues.show', [event, venue], queryStringParams)`

I think your first version is fine but it is a breaking change and starts to add complexity for the most basic use-case. Basically I don't want people who are just picking up the project to have a more complicated road to using the product.

I think the option I'm leaning to now is making `route()` just return a `new Router()`, overriding the `Router.prototype.toString` with all the stuff we currently have, and adding a `Router.prototype.withParams` or something (naming of this function is still up in the air) so we can chain params onto the existing router.

That way someone can do `route('posts.show', 1).withParams({color: red})`

[Here's a quick fiddle so you can see it in action.](https://jsfiddle.net/e0vb5580/14/)

I think this is the most Laravel way to do it. I want to abstract unnecessary complexity out into fluency so that it's hidden if you don't need it. Rather than making the base function super complex with tons of additional params, lets just add fluency. It sets a good pattern for the future as well when the next hot idea for a feature emerges. Otherwise 2 months from now we'll be scratching our heads trying to figure out how we're going to get more data into those 3 arguments.

**Comment by JesseLeite** [comment] 2017-08-18 12:39
>I think your first version is fine but it is a breaking change

```js
route('events.venues.show', [event, venue, queryStringParams])
```

^ That version is breaking change?  I thought the function just ignored extra params if it didn't need them in the route?

>I think the option I'm leaning to now is making route() just return a new Router(), overriding the Router.prototype.toString with all the stuff we currently have, and adding a Router.prototype.withParams or something (naming of this function is still up in the air) so we can chain params onto the existing router.

I absolutely love this!  I briefly thought it would be cool to chain a new method on, but didn't realize you could toString in JS 👌 👌 👌  Okay I'm going to leave this one to you :)

**Comment by DanielCoulbourne** [comment] 2017-08-18 17:16
Yeah you're right it isn't "breaking" I was super tired haha.

But yeah I think the fluency is the way to go.

**Comment by DanielCoulbourne** [comment] 2017-08-22 03:59
Done and Done!

**Closed by DanielCoulbourne** 2017-08-22 03:59 UTC
Labels: In Progress
