### ISSUE TITLE
The Protocol is cached

### ISSUE THREAD

**Issue by Ulyev-ad** [tightenco/ziggy#257] opened 2019-11-20 20:44 UTC
Caught the following error: when installing the library on the site with the http Protocol, the Protocol is cached and, even if I explicitly in routes/web prescribe URL:: forceScheme ('https'), then laravel change routes, and Ziggy does not change - baseProtocol: 'http'.

Clean all kinds of caches in laravel.

I use laravel6, php 7.3 and @routes. When generating in js file, the correct Protocol is used.

**Comment by bakerkretzmar** [comment] 2020-04-24 16:38
@Ulyev-ad just to clarify, if you change the protocol to `https` in your routes file and then run `php artisan view:clear`, does Ziggy correctly generate the new `https` routes?

**Comment by jakebathman** [comment] 2020-04-24 18:40
Closing this because we don't think it's an issue with Ziggy, but please let us know if there's more info or you have a reproducible test case.

**Closed by jakebathman** 2020-04-24 18:40 UTC
Labels: needs more info
