### ISSUE TITLE
route().current() broken when using with non-standard port number.

### ISSUE THREAD

**Issue by robertmylne** [tightenco/ziggy#142] opened 2018-03-13 23:28 UTC
I want to check if the named route `websites.index` is the currently viewed route in the browser. I can't work out why none of what I have tried is working though.

```
Route::get('websites', 'WebsiteController@index')->name('websites.index');

window.location.href
"http://localhost:3004/websites"

route().current("websites.index")
false

route('websites.index').url()
"//localhost:3004/websites"

route().current("websites")
false

route().current()
undefined

Ziggy.namedRoutes {
    websites.index: {
        domain: null
        methods: ["GET", "HEAD"]
        uri: "websites"
    }
}
```

**Comment by davidbankes** [comment] 2018-04-09 18:15
I think this is due to the port number. Recently ran into that in another build.

Perhaps consider renaming your issue "Broken when using with non-standard port number". I was about to open an issue like that, but it would basically a duplicate of what you seem to be facing.

**Comment by DanielCoulbourne** [comment] 2018-04-14 02:02
After further research it looks like the issue is protocol not port number. I actually have tests verifying port number. Let me hack on protocol real quick and see how it goes.

**Closed** 2018-04-14 02:13 UTC

**Comment by YannGrosjean** [comment] 2019-10-10 10:10
It's actually append to me with the port number : if I try to use route().current() on localhost:3000 the function return undefined, but work well on localhost:8000.

Any way to make it work ?

**Comment by atymic** [comment] 2020-02-18 21:18
Also having this issue as well, port 3002 :)

**Comment by atymic** [comment] 2020-02-18 21:22
As per above, seems to be wonky parsing. 
On the latest version.

 cc @DanielCoulbourne 

![image](https://user-images.githubusercontent.com/50683531/74778988-ce994000-52f0-11ea-968d-c6b8c58a5bfe.png)

**Comment by tnaffh** [comment] 2020-05-17 19:29
This issue is still there in the latest version, any solutions?
