### ISSUE TITLE
Ziggy Error: "" key is required for a route

### ISSUE THREAD

**Issue by filjoseph1989** [tightenco/ziggy#78] opened 2017-10-03 02:53 UTC
This is my actual code in javascript
```
    axios_get(route('User.edit', 1), function(data) {
      console.log(data);
    })
```
and I'm using the resource controller in laravel 5.5

but I got this error

Ziggy Error: "User" key is required for route "User.edit"

In your code;
```
      return url.replace(
            /\{([^}]+)\}/gi,
            function (tag) {
                var key = tag.replace(/\{|\}/gi, '');
                if (params[key] === undefined) {
                    throw 'Ziggy Error: "' + key + '" key is required for route "' + name + '"';
                }
                return params[key];
            }
        );
```
It point to this part
`throw 'Ziggy Error: "' + key + '" key is required for route "' + name + '"';`

**Comment by DanielCoulbourne** [comment] 2017-10-04 21:01
Thanks for the report. I have 20% time coming up friday when I'll knock out this and a bunch of other issues

**Comment by DanielCoulbourne** [comment] 2017-10-23 22:38
Which version of Ziggy are you running?

**Comment by danieltorscho** [comment] 2017-12-01 10:11
I have the same error log, reproduced in the same way.

**Comment by DanielCoulbourne** [comment] 2017-12-01 19:18
Great! Can you provide me the section in question of your Laravel Routes file?

**Comment by DanielCoulbourne** [comment] 2018-01-26 22:26
Closing this for lack of info.

**Closed by DanielCoulbourne** 2018-01-26 22:26 UTC

**Comment by mazyvan** [comment] 2018-08-29 03:46
I'm getting this too. It seams like this happens only when the second parameter is a string

**Comment by DanielCoulbourne** [comment] 2018-08-29 04:13
What versions of ziggy and laravel. Please include the code that makes it happen and your routs file containing that route so I can duplicate

**Comment by butcherman** [comment] 2019-10-29 02:07
I know this is a little old, but I had this issue as well, but figured out what was going on.  The problem is that the ID parameter for the route does not exist until the AJAX call is completed.  So, when the page loads, the error is triggered because the variable is not there yet.

My solution:
Create a null variable that is assigned to the route, and fill it after the AJAX call.  This seems to work for me.

```
data() {
     details: [], //  My data that is filled in by the AJAX call
     hash:  '',   //  My blank variable
     url:  route('my.path', hash);   //  route that needs the variable loaded by AJAX
}
methods: {
     getStuff() {
          axios.get(this.route('ajax.route')
               .then(res => {
                    this.details = res.data;
                    this.hash = res.data.hash;
               )};
     }
}
```
