### ISSUE TITLE
Allow importing route function (and data) instead of storing them globally

### ISSUE THREAD

**Issue by hackel** [tightenco/ziggy#24] opened 2017-08-10 23:04 UTC
I love the idea of this package.  I just wish it didn't pollute the global window namespace.  Ideally, I would be able to simply `import { route } from 'ziggy';` in my JS (e.g. Vue component or whatever), and it would automatically pull the data in with it, either from a locally-cached JSON file or even an API call.

It might even be possible to limit the included routes to those that are actually referenced by the route function, for cases where a project has a ton of routes.  Perhaps using Webpack tree-shaking or something similar.

Keep up the good work!

**Comment by mattstauffer** [comment] 2017-08-11 00:21
Hey @hackel! The way we are imagining this is here: https://github.com/tightenco/ziggy/issues/22 would that solve for your use case?

**Comment by DanielCoulbourne** [comment] 2017-08-11 22:25
@hackel as of now you can actually pull in the `route()` function, as it's included (and exported) in `src/js/route.js`

It doesn't have a good way to get the data yet, but we are seriously considering adding an endpoint to get it from ( 🙌 Issue #1 ) so I think what you want will be possible very very soon 😄

**Comment by DanielCoulbourne** [comment] 2017-08-11 22:27
I do agree about the global namespace. I think namespacing the data to `ziggy` is probably a good idea. I don't want to remove the `route()` function from the global namespace just yet, but I could probably be convinced.

**Comment by lindyhopchris** [comment] 2017-08-14 10:02
+1 on this, I'm using Ember.js for my frontend so would be great to be able to include this as a dependency via yarn and import as a module.

**Comment by DanielCoulbourne** [comment] 2017-08-14 23:49
@lindyhopchris unfortunately I have no plans of making Ziggy an NPM package as of now since maintaining separate NPM and Composer packages with dependencies on each other sounds like a versioning nightmare 😢 

I may try to come up with a solution for easily including JS from the Composer package in NPM projects, but it's a relatively low priority as of now. I'm open to pull requests though if you have a good idea on how to implement it. Feel free to open a new issue if you'd like to work on that together.

I'm closing this issue because it's a duplicate of a few other issues combined and I'd rather keep those two concepts separated.

For people who are interested in dumping routes data to a file to be included in your JS, check out #22 

For those interested in an API endpoint for retrieving routes from the server by AJAX (or whatever) head on over to #1

**Closed by DanielCoulbourne** 2017-08-14 23:49 UTC
Labels: enhancement

**Comment by lindyhopchris** [comment] 2017-08-15 04:50
@DanielCoulbourne no problem, totally understand!

**Comment by mikerockett** [comment] 2018-01-06 08:02
Not sure if this is good practice or anything, but I created an in-app provider that registers a composer to pass along my routes to each view. Only the routes. Then, on the webpack side, I’m simply importing the script directly from vendor. This is where my question lies… Bad practice?
